#!/bin/sh

if [ -z "$1" ]; then
	cat <<-EOF
	usage: generateXsamples NUM_OF_SAMPLES
EOF
	exit 1
fi

gensample ()
{
    printf '{"uv": 1, "light": 1, "accel_x": 1, "accel_y": 1, "accel_z": 1, "col_red": 255, "col_green": 255, "col_blue": 255, "col_clear": 1, "col_temp": 1,"timestamp": "%s"}' "$(date --date="@$1" -Iseconds)"
}

printf '{"samples": [\n'
printf '\t%s' "$(gensample 1)"
for d in `seq 2 $1`; do
	printf ',\n\t%s' "$(gensample "$d")"
done
printf '\n]}\n'

