version = 0.1

# These sections are organised by the primary users ("UseCase") of the backend interface.

# Different usecases reside in different CloudFormation stacks (and VPCs).

# Within each usecase, the development environments ("dev" and
# "localhost") share a stack and VPC.  This stack and VPC for the
# development environments is *not* shared with the "prod" (not
# implemented here) environment.

[app-dev.global.parameters]
stack_name = "backend-app-dev"
[app-dev.deploy.parameters]
resolve_s3 = true
s3_prefix = "backend-app-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UseCase=\"app\" Environment=\"dev\" VpcCIDR=\"10.8.0.0/16\" PublicSubnet1CIDR=\"10.8.10.0/24\" PublicSubnet2CIDR=\"10.8.11.0/24\" PrivateSubnet1CIDR=\"10.8.20.0/24\" PrivateSubnet2CIDR=\"10.8.21.0/24\""



[server-dev.global.parameters]
stack_name = "backend-server-dev"
[server-dev.deploy.parameters]
resolve_s3 = true
s3_prefix = "backend-server-dev"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UseCase=\"server\" Environment=\"dev\" VpcCIDR=\"10.16.0.0/16\" PublicSubnet1CIDR=\"10.16.10.0/24\" PublicSubnet2CIDR=\"10.16.11.0/24\" PrivateSubnet1CIDR=\"10.16.20.0/24\" PrivateSubnet2CIDR=\"10.16.21.0/24\""

[server-localhost.global.parameters]
stack_name = "backend-server-dev"
[server-localhost.deploy.parameters]
stack_name = "backend-server-dev"
resolve_s3 = true
s3_prefix = "backend-server-dev"
confirm_changeset = true
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UseCase=\"server\" Environment=\"localhost\" WebsiteStackName=\"frontend\" WebsiteLocalhostPort=\"3000\" VpcCIDR=\"10.16.0.0/16\" PublicSubnet1CIDR=\"10.16.10.0/24\" PublicSubnet2CIDR=\"10.16.11.0/24\" PrivateSubnet1CIDR=\"10.16.20.0/24\" PrivateSubnet2CIDR=\"10.16.21.0/24\""
image_repositories = []



[website-dev.global.parameters]
stack_name = "backend-website-dev"
[website-dev.deploy.parameters]
stack_name = "backend-website-dev"
resolve_s3 = true
s3_prefix = "backend-website-dev"
confirm_changeset = true
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UseCase=\"website\" Environment=\"dev\" WebsiteStackName=\"frontend\" VpcCIDR=\"10.24.0.0/16\" PublicSubnet1CIDR=\"10.24.10.0/24\" PublicSubnet2CIDR=\"10.24.11.0/24\" PrivateSubnet1CIDR=\"10.24.20.0/24\" PrivateSubnet2CIDR=\"10.24.21.0/24\""
image_repositories = []

[website-localhost.global.parameters]
stack_name = "backend-website-dev"
[website-localhost.deploy.parameters]
stack_name = "backend-website-dev"
resolve_s3 = true
s3_prefix = "backend-website-dev"
confirm_changeset = true
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UseCase=\"website\" Environment=\"localhost\" WebsiteStackName=\"frontend\" VpcCIDR=\"10.24.0.0/16\" PublicSubnet1CIDR=\"10.24.10.0/24\" PublicSubnet2CIDR=\"10.24.11.0/24\" PrivateSubnet1CIDR=\"10.24.20.0/24\" PrivateSubnet2CIDR=\"10.24.21.0/24\""
image_repositories = []



# Here we integrate everyone's stuff


[all-dev.global.parameters]
stack_name = "backend-all-dev"
[all-dev.deploy.parameters]
resolve_s3 = true
s3_prefix_name = "backend-all-dev"
confirm_changeset = true
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UseCase=\"all\" Environment=\"dev\" WebsiteStackName=\"frontend\" VpcCIDR=\"10.128.0.0/16\" PublicSubnet1CIDR=\"10.128.10.0/24\" PublicSubnet2CIDR=\"10.128.11.0/24\" PrivateSubnet1CIDR=\"10.128.20.0/24\" PrivateSubnet2CIDR=\"10.128.21.0/24\""
image_repositories = []

# BUT localhost website uses same VPC and stack as dev

[all-localhost.global.parameters]
stack_name = "backend-all-dev"
[all-localhost.deploy.parameters]
resolve_s3 = true
s3_prefix_name = "backend-all-dev"
confirm_changeset = true
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UseCase=\"all\" Environment=\"localhost\" WebsiteStackName=\"frontend\" VpcCIDR=\"10.128.0.0/16\" PublicSubnet1CIDR=\"10.128.10.0/24\" PublicSubnet2CIDR=\"10.128.11.0/24\" PrivateSubnet1CIDR=\"10.128.20.0/24\" PrivateSubnet2CIDR=\"10.128.21.0/24\""
image_repositories = []


# Special usecases

# Put the build config for more usecases here.
