AWSTemplateFormatVersion: "2010-09-09"
Description: SAM template for cloud backend
Transform: AWS::Serverless-2016-10-31

# TODO: set up dev and "prod" (ie, OK for non-cloud devs to use) environments

Parameters:
  # EnvironmentName:
  #   Description: An environment name that is prefixed to resource names
  #   Type: String

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.8.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.8.10.0/24
  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.8.11.0/24
  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.8.20.0/24
  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.8.21.0/24
# Mappings:

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: backend-vpc
      # Tags:
      #   - Key: Name
      #     Value: !Ref EnvironmentName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Internet Gateway
    # Properties:
      # Tags:
      #   - Key: Name
      #     Value: !Ref EnvironmentName
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet (AZ1)
      # Tags:
      #   - Key: Name
      #     Value: !Sub ${EnvironmentName} Public Subnet (AZ1)
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet (AZ2)
      # Tags:
      #   - Key: Name
      #     Value: !Sub ${EnvironmentName} Public Subnet (AZ2)
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Private Subnet (AZ1)
      # Tags:
      #   - Key: Name
      #     Value: !Sub ${EnvironmentName} Private Subnet (AZ1)
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Private Subnet (AZ2)
      # Tags:
      #   - Key: Name
      #     Value: !Sub ${EnvironmentName} Private Subnet (AZ2)

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Public Routes
      # Tags:
      #   - Key: Name
      #     Value: !Sub ${EnvironmentName} Public Routes
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Private Routes (AZ1)
      # Tags:
      #   - Key: Name
      #     Value: !Sub ${EnvironmentName} Private Routes (AZ1)
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1
  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Private Routes (AZ2)
      # Tags:
      #   - Key: Name
      #     Value: !Sub ${EnvironmentName} Private Routes (AZ2)
  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      SubnetId: !Ref PrivateSubnet2

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ProjectLambdaRole
      Description: "Role to allow lambda functions to do everything in the set of things our backend needs to do (ie, it's not minimal)"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        # If we want it later:
        # - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: AllowReadSecretValue
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !GetAtt Database.MasterUserSecret.SecretArn

  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.secretsmanager
      VpcId: !Ref VPC
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecretsManagerSecurityGroup
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
  SecretsManagerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: secretsmanager-sg
      GroupDescription: Allow inbound HTTP traffic from authorised applications for Secrets Manager
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId:
            Ref: SecretsAccessSecurityGroup
  SecretsAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: secretsmanager-access-sg
      GroupDescription: Security group for applications allowed to access Secrets Manager
      VpcId: !Ref VPC
      # no in/egress rules since none needed

  NoIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "no-ingress-sg"
      GroupDescription: "Security group with no ingress rule"
      VpcId: !Ref VPC
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for database (mandatory for VPC DBs!)
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: db-sg
      GroupDescription: Allow inbound postgres traffic from authorised applications for database
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId:
            Ref: DBAccessSecurityGroup
  DBAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: db-access-sg
      GroupDescription: Security group for services allowed to access database
      VpcId: !Ref VPC
      # no in/egress rules since none needed
  # Database
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      StorageType: gp2
      AllocatedStorage: 20  # GiB
      DBInstanceClass: db.t3.micro  # free-tier acceptable
      # Use Default DBName of `postgres` for PostgreSQL
      DBName: postgres
      MasterUsername: postgres
      ManageMasterUserPassword: true  # in AWS Secrets Manager
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      EnablePerformanceInsights: true
      EnableCloudwatchLogsExports:
        - postgresql
        - upgrade
      BackupRetentionPeriod: 7  # days
      StorageEncrypted: true
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
  # TODO: Use parameter store for location of cert layer?
  # See https://dev.to/leading-edje/aws-lambda-layer-for-private-certificates-465j
  LayerCACertificates:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: layer-ca-certs
      Description: Certificates to connect to DB via TLS
      ContentUri: lambda/layers/certs/
      CompatibleRuntimes:
        - nodejs20.x
      # RetentionPolicy: Retain

  # API Gateway
  API:
    Type: AWS::Serverless::Api
    DependsOn: APICloudWatchRoleArn
    Properties:
      StageName: dev
      # TODO: more restrictive?
      Cors: "'*'"
      MethodSettings:
        - LoggingLevel: INFO
          MetricsEnabled: true
          ResourcePath: '/*'
          HttpMethod: '*'
      # Domain:
      #   DomainName: api.neox.co.nz

  # Set CloudWatch Logs role ARN in account settings.
  APICloudWatchRoleArn:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt APICloudWatchRole.Arn
  APICloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service:
              - apigateway.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
  # NOTE: the lambdas seem to be automatically integrated via lambda proxy integration
  # Lambda
  FuncSamplesSearch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: action-samples-search
      CodeUri: lambda/functions/action-samples-search/
      Handler: index.handler
      Runtime: nodejs20.x
      Layers:
        - !Ref LayerDepsJS
        - !Ref LayerCACertificates
      Environment:
        Variables:
          PGHOST: !GetAtt Database.Endpoint.Address
          # Default PGDATABASE is the user which we will get from the SecretsManager Secret
          PGPORT: !GetAtt Database.Endpoint.Port
          DB_SECRET_ARN: !GetAtt Database.MasterUserSecret.SecretArn
          SSL_CERT_FILE: /opt/global-bundle.pem
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref DBAccessSecurityGroup
          - !Ref SecretsAccessSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /samples
            Method: get
            RestApiId: !Ref API
  FuncSamplesAdd:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: action-samples-add
      CodeUri: lambda/functions/action-samples-add/
      Handler: index.handler
      Runtime: nodejs20.x
      Layers:
        - !Ref LayerDepsJS
        - !Ref LayerCACertificates
      Environment:
        Variables:
          PGHOST: !GetAtt Database.Endpoint.Address
          # Default PGDATABASE is the user which we will get from the SecretsManager Secret
          PGPORT: !GetAtt Database.Endpoint.Port
          DB_SECRET_ARN: !GetAtt Database.MasterUserSecret.SecretArn
          SSL_CERT_FILE: /opt/global-bundle.pem
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref DBAccessSecurityGroup
          - !Ref SecretsAccessSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /samples
            Method: post
            RestApiId: !Ref API
  FuncMetaSetupDB:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meta-setupdb-testdata
      CodeUri: lambda/functions/meta-setupdb-testdata/
      Handler: index.handler
      Runtime: nodejs20.x
      Layers:
        - !Ref LayerDepsJS
        - !Ref LayerCACertificates
      Environment:
        Variables:
          PGHOST: !GetAtt Database.Endpoint.Address
          # Default PGDATABASE is the user which we will get from the SecretsManager Secret
          PGPORT: !GetAtt Database.Endpoint.Port
          DB_SECRET_ARN: !GetAtt Database.MasterUserSecret.SecretArn
          SSL_CERT_FILE: /opt/global-bundle.pem
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref DBAccessSecurityGroup
          - !Ref SecretsAccessSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
  LayerDepsJS:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: layer-lib-js
      Description: Common code and dependencies for JS lambda functions
      # ContentUri: s3://proj-deploy-artifacts/layer-deps-js.zip
      ContentUri: lambda/layers/project-lib-js/
      CompatibleRuntimes:
        - nodejs20.x
    Metadata:
      BuildMethod: nodejs20.x

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

  PublicSubnets:
    Description: A list of the public subnets
    Value: !Join [ ",", [ !Ref PublicSubnet1, !Ref PublicSubnet2 ]]
  PrivateSubnets:
    Description: A list of the private subnets
    Value: !Join [ ",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]]
  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnet1
  PublicSubnet2:
    Description: A reference to the public subnet in the 2nd Availability Zone
    Value: !Ref PublicSubnet2
  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnet1
  PrivateSubnet2:
    Description: A reference to the private subnet in the 2nd Availability Zone
    Value: !Ref PrivateSubnet2

  NoIngressSecurityGroup:
    Description: Security group with no ingress rule
    Value: !Ref NoIngressSecurityGroup
  DatabaseSecurityGroup:
    Description: Security group for database
    Value: !Ref DatabaseSecurityGroup
  DBAccessSecurityGroup:
    Description: Security group for services allowed to access database
    Value: !Ref DBAccessSecurityGroup
  SecretsManagerVPCEndpoint:
    Description: Endpoint for hosts inside VPC to access Secrets Manager
    Value: !Ref SecretsManagerVPCEndpoint
  SecretsManagerSecurityGroup:
    Description: Security group for Secrets Manager
    Value: !Ref SecretsManagerSecurityGroup
  SecretsAccessSecurityGroup:
    Description: Security group for applications allowed to access Secrets Manager
    Value: !Ref SecretsAccessSecurityGroup

  Database:
    Description: Database for samples, etc
    Value: !Ref Database
