version = 0.1
[default.deploy.parameters]
stack_name = "frontend-subtemplates"
resolve_s3 = true
s3_prefix = "frontend-subtemplates"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
